cbeta_id: T13n0421
title: 奋迅王问经
translator: 元魏 瞿昙般若流支译
dynasty: 元魏
category: 大集
bulei:
  section_code: "08"
  section: 大集部类
  group: T0398-424 etc. 大集经余 T13, X21,74, A114
  path:
    - 08 大集部类
    - T0398-424 etc. 大集经余 T13, X21,74, A114
  kind: 经
  source: bulei.txt
juan_count: 2
source_xml:
  - T/T13/T13n0421.xml
