cbeta_id: T37n1748
title: 无量寿经连义述文赞
translator: 新罗 璟兴撰
dynasty: 新罗
category: 宝积
bulei:
  section_code: "06"
  section: 宝积部类
  group: T0360-64 无量寿经 etc. T11-12／疏 T37,85
  path:
    - 06 宝积部类
    - T0360-73 净土经 T11-12／论 T26a／疏 T37,40b,85
    - T0360-64 无量寿经 etc. T11-12／疏 T37,85
    - T1745-48 无量寿经疏 T37
  kind: 疏
  source: bulei.txt
juan_count: 3
source_xml:
  - T/T37/T37n1748.xml
