cbeta_id: T48n2017
title: 万善同归集
translator: 宋 延寿述
dynasty: 宋
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: T2016-18 永明著作
  path:
    - 17 禅宗部类
    - T2007-25, CC0002 坛经等历代禅宗典籍 T48, CC002, G155
    - T2016-18 永明著作
  kind: 经
  source: bulei.txt
juan_count: 3
source_xml:
  - T/T48/T48n2017.xml
