cbeta_id: ZW04na023
title: 「中国社会科学院佛教研究中心成立暨佛教研究与新时期的文化建设研讨会」纪要
category: 新编（新增及近现代文献）
bulei:
  section_code: "23"
  section: 新编部类
  group: ZW0033-44 第四辑
  path:
    - 23 新编部类
    - ZW0001-103 藏外佛教文献
    - ZW0033-44 第四辑
  kind: 疏
  source: bulei.txt
juan_count: 1
source_xml:
  - ZW/ZW04/ZW04nA023.xml
