cbeta_id: TX20n0012
title: 太虚大师全书．第十二编　宗体论
translator: 民国 释太虚着
dynasty: 民国
category: 新编（新增及近现代文献）
bulei:
  section_code: "23"
  section: 新编部类
  group: 论藏
  path:
    - 23 新编部类
    - TX0001-20 太虚大师全书
    - 论藏
  kind: 疏
  source: bulei.txt
juan_count: 1
source_xml:
  - TX/TX20/TX20n0012.xml
