cbeta_id: X64n1264
title: 禅林宝训拈颂
translator: 清 行盛着　超记录
dynasty: 清
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: X1260-76, JB128-29 杂着(2) X64, J23 列祖提纲录 etc.
  path:
    - 17 禅宗部类
    - X1260-76, JB128-29 杂着(2) X64, J23 列祖提纲录 etc.
  kind: 疏
  source: bulei.txt
juan_count: 1
source_xml:
  - X/X64/X64n1264.xml
