cbeta_id: J34nB312
title: 天界觉浪盛禅师嘉禾语录
translator: 明 道盛说　大枢．大英录　谭贞默序
dynasty: 明
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: JB272-313 语录别集(9) J32-34 明州天童景德禅寺宏智觉禅师语录 etc.
  path:
    - 17 禅宗部类
    - JB272-313 语录别集(9) J32-34 明州天童景德禅寺宏智觉禅师语录 etc.
  kind: 经
  source: bulei.txt
juan_count: 1
source_xml:
  - J/J34/J34nB312.xml
