cbeta_id: ZW11na067
title: 《藏外佛教文献》总目录（第一辑～第十二辑）（ZW第11卷）
category: 新编（新增及近现代文献）
bulei:
  section_code: "23"
  section: 新编部类
  group: ZW0089-96 第十一辑
  path:
    - 23 新编部类
    - ZW0001-103 藏外佛教文献
    - ZW0089-96 第十一辑
  kind: 疏
  source: bulei.txt
juan_count: 1
source_xml:
  - ZW/ZW11/ZW11nA067.xml
