cbeta_id: T18n0850
title: 摄大毘卢遮那成佛神变加持经入莲华胎藏海会悲生曼荼攞广大念诵仪轨供养方便会
translator: 唐 输婆迦罗译
dynasty: 唐
category: 密教（真言宗、陀罗尼、仪轨）
bulei:
  section_code: "10"
  section: 密教部类
  group: T0848-64 大日经 etc. T18
  path:
    - 10 密教部类
    - T18-21, X01-02,23, C071, F24,27-28, L135, G052 密教部
    - T0848-64 大日经 etc. T18
  kind: 经
  source: bulei.txt
juan_count: 3
source_xml:
  - T/T18/T18n0850.xml
