cbeta_id: GA012n0010
title: 明州阿育王山志(第9卷-第10卷)
translator: 明 郭子章撰
dynasty: 明
category: 史传（僧传、寺志、编年史料）
bulei:
  section_code: "23"
  section: 新编部类
  group: GA0002-89 中国佛寺史志汇刊选录
  path:
    - 23 新编部类
    - GA0002-89, GB0109 中国佛寺志
    - GA0002-89 中国佛寺史志汇刊选录
  kind: 疏
  source: short
juan_count: 2
source_xml:
  - GA/GA012/GA012n0010.xml
