cbeta_id: X15n0306
title: 楞严经观心定解
translator: 清 灵耀述
dynasty: 清
category: 密教（真言宗、陀罗尼、仪轨）
bulei:
  section_code: "10"
  section: 密教部类
  group: T1799 etc. 首楞严义疏注经 etc. T39, X10-16, P168,185
  path:
    - 10 密教部类
    - T39, X10-16,23,  P168,185 密教疏
    - T1799 etc. 首楞严义疏注经 etc. T39, X10-16, P168,185
    - X0304-6 楞严经观心定解 etc. X15
  kind: 疏
  source: bulei.txt
juan_count: 10
source_xml:
  - X/X15/X15n0306.xml
