cbeta_id: X57n0956
title: 山家义苑
translator: 宋 可观述　智增证
dynasty: 宋
category: 法华
bulei:
  section_code: "04"
  section: 法华部类
  group: T46, X55-57,74, G069,157, P167,189 天台宗
  path:
    - 04 法华部类
    - T46, X55-57,74, G069,157, P167,189 天台宗
  kind: 疏
  source: bulei.txt
juan_count: 2
source_xml:
  - X/X57/X57n0956.xml
