cbeta_id: T21n1306
title: 北斗七星护摩秘要仪轨
translator: 唐 不空述
dynasty: 唐
category: 密教（真言宗、陀罗尼、仪轨）
bulei:
  section_code: "10"
  section: 密教部类
  group: T1199-1420 etc. 陀罗尼经典 T21, X01-02
  path:
    - 10 密教部类
    - T18-21, X01-02,23, C071, F24,27-28, L135, G052 密教部
    - T1199-1420 etc. 陀罗尼经典 T21, X01-02
    - T1299-1312 宿曜吉凶法
  kind: 经
  source: bulei.txt
juan_count: 1
source_xml:
  - T/T21/T21n1306.xml
