cbeta_id: N70n0036
title: 一切善见律注序
translator: 佛音译述　悟醒译
dynasty: 佛音译述
category: 论集（杂论、通论）
bulei:
  section_code: "22"
  section: 南传大藏经部类
  group: N0031-38 藏外 N63-70
  path:
    - 22 南传大藏经部类
    - N0031-38 藏外 N63-70
  kind: 经
  source: bulei.txt
juan_count: 1
source_xml:
  - N/N70/N70n0036.xml
