cbeta_id: ZW06n0056
title: 进新译大方广佛花严经表
translator: 弘景撰　方广锠整理
category: 新编（新增及近现代文献）
bulei:
  section_code: "23"
  section: 新编部类
  group: ZW0051-57 第六辑
  path:
    - 23 新编部类
    - ZW0001-103 藏外佛教文献
    - ZW0051-57 第六辑
    - ZW0056 敦煌经录
  kind: 疏
  source: bulei.txt
juan_count: 1
source_xml:
  - ZW/ZW06/ZW06n0056.xml
