cbeta_id: T37n1746
title: 无量寿经义疏
translator: 隋 吉藏撰
dynasty: 隋
category: 宝积
bulei:
  section_code: "06"
  section: 宝积部类
  group: T0360-64 无量寿经 etc. T11-12／疏 T37,85
  path:
    - 06 宝积部类
    - T0360-73 净土经 T11-12／论 T26a／疏 T37,40b,85
    - T0360-64 无量寿经 etc. T11-12／疏 T37,85
    - T1745-48 无量寿经疏 T37
  kind: 疏
  source: bulei.txt
juan_count: 1
source_xml:
  - T/T37/T37n1746.xml
