cbeta_id: J27nB193
title: 隐元禅师语录
translator: 清 隆琦说　海宁等编
dynasty: 清
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: JB189-221 语录别集(7) J27-28 三宜盂禅师语录 etc.
  path:
    - 17 禅宗部类
    - JB189-221 语录别集(7) J27-28 三宜盂禅师语录 etc.
  kind: 经
  source: bulei.txt
juan_count: 16
source_xml:
  - J/J27/J27nB193.xml
