cbeta_id: X22n0426
title: 阿弥陀经疏钞问辩
translator: 明 袾宏述
dynasty: 明
category: 净土宗
bulei:
  section_code: "16"
  section: 净土宗部类
  group: T0366-67 etc. 阿弥陀经 etc. T12a, X01／疏 T37, X22
  path:
    - 16 净土宗部类
    - T0310 etc. 净土经 T11-12, X01-02,16, CC006／论 T26a／疏 T37,40b,85, X22
    - T0366-67 etc. 阿弥陀经 etc. T12a, X01／疏 T37, X22
  kind: 疏
  source: bulei.txt
juan_count: 1
source_xml:
  - X/X22/X22n0426.xml
