cbeta_id: TX16n0008
title: 太虚大师全书．第八编　律释
translator: 民国 释太虚着
dynasty: 民国
category: 新编（新增及近现代文献）
bulei:
  section_code: "23"
  section: 新编部类
  group: 制藏
  path:
    - 23 新编部类
    - TX0001-20 太虚大师全书
    - 制藏
  kind: 疏
  source: bulei.txt
juan_count: 3
source_xml:
  - TX/TX16/TX16n0008.xml
