cbeta_id: T05n0220
title: 大般若波罗蜜多经
translator: 唐 玄奘译
dynasty: 唐
category: 般若
zaijia:
  section: 般若部類
  topic: 上品般若(大般若經第1會)
  kind: 经
juan_count: 600
source_xml: []
description: 整经目录索引；正文分卷见：大般若波罗蜜多经(第1卷-第200卷)_唐玄奘译_200卷a、大般若波罗蜜多经(第201卷-第400卷)_唐玄奘译_200卷b、大般若波罗蜜多经(第401卷-第600卷)_唐玄奘译_137卷c、大般若波罗蜜多经(第401卷-第600卷)_唐玄奘译_1卷g、大般若波罗蜜多经(第401卷-第600卷)_唐玄奘译_1卷h、大般若波罗蜜多经(第401卷-第600卷)_唐玄奘译_1卷i、大般若波罗蜜多经(第401卷-第600卷)_唐玄奘译_1卷l、大般若波罗蜜多经(第401卷-第600卷)_唐玄奘译_1卷m、大般若波罗蜜多经(第401卷-第600卷)_唐玄奘译_28卷d、大般若波罗蜜多经(第401卷-第600卷)_唐玄奘译_2卷f、大般若波罗蜜多经(第401卷-第600卷)_唐玄奘译_2卷n、大般若波罗蜜多经(第401卷-第600卷)_唐玄奘译_5卷j、大般若波罗蜜多经(第401卷-第600卷)_唐玄奘译_5卷k、大般若波罗蜜多经(第401卷-第600卷)_唐玄奘译_8卷e、大般若波罗蜜多经(第401卷-第600卷)_唐玄奘译_8卷o
