cbeta_id: T48n2019B
title: 诫初心学人文
translator: 高丽 知讷撰
dynasty: 高丽
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: T2019-20 知讷著作
  path:
    - 17 禅宗部类
    - T2007-25, CC0002 坛经等历代禅宗典籍 T48, CC002, G155
    - T2019-20 知讷著作
  kind: 经
  source: bulei.txt
juan_count: 1
source_xml:
  - T/T48/T48n2019B.xml
