cbeta_id: T51n2078
title: 传法正宗记
translator: 宋 契嵩编
dynasty: 宋
category: 史传（僧传、寺志、编年史料）
bulei:
  section_code: "18"
  section: 史传部类
  group: T2078-80 传法正宗记 etc.
  path:
    - 18 史传部类
    - T2075-80,1998B, X1553-1622, JB125 禅宗传 T51,47, X78-87, J23, P154-55
    - T2078-80 传法正宗记 etc.
  kind: 疏
  source: bulei.txt
juan_count: 9
source_xml:
  - T/T51/T51n2078.xml
