cbeta_id: X85n1593
title: 禅宗正脉
translator: 明 如卺集
dynasty: 明
category: 史传（僧传、寺志、编年史料）
bulei:
  section_code: "18"
  section: 史传部类
  group: T2076, X1553-59,64-66,93 五灯时期灯录
  path:
    - 18 史传部类
    - T2075-80,1998B, X1553-1622, JB125 禅宗传 T51,47, X78-87, J23, P154-55
    - T2076, X1553-59,64-66,93 五灯时期灯录
    - X1564-66,93 五灯会元 etc.
  kind: 疏
  source: bulei.txt
juan_count: 10
source_xml:
  - X/X85/X85n1593.xml
