cbeta_id: J30nB259
title: 怡山礼佛发愿文略释
translator: 清 书玉略释并序跋　有事义（依驹本印）
dynasty: 清
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: JB090-497 杂着(4) J20-21,23,25-40 续原教论 etc.
  path:
    - 17 禅宗部类
    - JB090-497 杂着(4) J20-21,23,25-40 续原教论 etc.
  kind: 疏
  source: bulei.txt
juan_count: 1
source_xml:
  - J/J30/J30nB259.xml
