cbeta_id: J40nB486
title: 鉴堂一禅师语录
translator: 清 一说　明满．明慧等录　杜允贞序（依驹本增入并印）
dynasty: 清 一说
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: JB472-494 语录别集(14) J40 大博干禅师语录 etc.
  path:
    - 17 禅宗部类
    - JB472-494 语录别集(14) J40 大博干禅师语录 etc.
  kind: 经
  source: bulei.txt
juan_count: 1
source_xml:
  - J/J40/J40nB486.xml
