cbeta_id: X61n1157
title: 净土决
translator: 明 李贽集
dynasty: 明
category: 净土宗
bulei:
  section_code: "16"
  section: 净土宗部类
  group: T1974-77, X1154-58,60,62-68,1207 明朝著作
  path:
    - 16 净土宗部类
    - T1957-84 etc. 净土宗 T47, X02,61-62,74
    - T1974-77, X1154-58,60,62-68,1207 明朝著作
  kind: 疏
  source: bulei.txt
juan_count: 1
source_xml:
  - X/X61/X61n1157.xml
