cbeta_id: X35n0648
title: 高王观音经注释
translator: 清 周上智录出
dynasty: 清
category: 法华
bulei:
  section_code: "04"
  section: 法华部类
  group: F0016 大王观世音经 F01／疏 X35
  path:
    - 04 法华部类
    - T09a, F01 法华经／疏 T33-34,85, X27-35, G124, L115-116, P184-185／论 T34
    - F0016 大王观世音经 F01／疏 X35
  kind: 疏
  source: bulei.txt
juan_count: 1
source_xml:
  - X/X35/X35n0648.xml
