cbeta_id: J28nB215
title: 颂古合响集
translator: 明 彻（尼）．符（尼）合颂　张有誉辑并序
dynasty: 明
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: JB090-497 杂着(4) J20-21,23,25-40 续原教论 etc.
  path:
    - 17 禅宗部类
    - JB090-497 杂着(4) J20-21,23,25-40 续原教论 etc.
  kind: 经
  source: bulei.txt
juan_count: 1
source_xml:
  - J/J28/J28nB215.xml
