cbeta_id: T24n1499
title: 菩萨戒羯磨文
translator: 弥勒菩萨说  唐 玄奘译
category: 律部（戒律、僧制）
bulei:
  section_code: "11"
  section: 律部类
  group: T1484-1504, A1505 菩萨戒藏 T24, A114／疏 T40a,85, X38-39
  path:
    - 11 律部类
    - T22-24,40a, X39-40,44, A114 律部／疏 T40a,85, X38-39,44, F02
    - T1484-1504, A1505 菩萨戒藏 T24, A114／疏 T40a,85, X38-39
  kind: 疏
  source: bulei.txt
juan_count: 1
source_xml:
  - T/T24/T24n1499.xml
