cbeta_id: T17n0740
title: 佛说頞多和多耆经
translator: 失译
category: 经集（零散大乘经典）
bulei:
  section_code: "09"
  section: 经集部类
  group: T0721-59, X0023 业道经 etc. T17, X01
  path:
    - 09 经集部类
    - T0721-59, X0023 业道经 etc. T17, X01
  kind: 疏
  source: bulei.txt
juan_count: 1
source_xml:
  - T/T17/T17n0740.xml
