cbeta_id: J26nB178
title: 费隐禅师语录
translator: 明 通容说　隆琦等编　附纪年录　行观．王谷同集　徐昌治．董行证较　行宗．行古重订刻
dynasty: 明
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: JA158,B137-188 语录别集(6) J10,24-26 密云禅师语录 etc.
  path:
    - 17 禅宗部类
    - JA158,B137-188 语录别集(6) J10,24-26 密云禅师语录 etc.
  kind: 经
  source: bulei.txt
juan_count: 14
source_xml:
  - J/J26/J26nB178.xml
