cbeta_id: X72n1434
title: 见如元谧禅师语录
translator: (门人)道璞集
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: X1428-44 语录别集(4) X72 净慈慧晖禅师语录 etc.
  path:
    - 17 禅宗部类
    - X1428-44 语录别集(4) X72 净慈慧晖禅师语录 etc.
  kind: 经
  source: bulei.txt
juan_count: 1
source_xml:
  - X/X72/X72n1434.xml
