cbeta_id: X72n1437
title: 永觉元贤禅师广录
translator: (嗣法)道霈重编
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: X1428-44 语录别集(4) X72 净慈慧晖禅师语录 etc.
  path:
    - 17 禅宗部类
    - X1428-44 语录别集(4) X72 净慈慧晖禅师语录 etc.
  kind: 经
  source: bulei.txt
juan_count: 30
source_xml:
  - X/X72/X72n1437.xml
