cbeta_id: J33nB284
title: 益州嵩山野竹禅师后录
translator: 清 福慧说　洪希等编
dynasty: 清
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: JB272-313 语录别集(9) J32-34 明州天童景德禅寺宏智觉禅师语录 etc.
  path:
    - 17 禅宗部类
    - JB272-313 语录别集(9) J32-34 明州天童景德禅寺宏智觉禅师语录 etc.
  kind: 经
  source: bulei.txt
juan_count: 8
source_xml:
  - J/J33/J33nB284.xml
