cbeta_id: L153n1637
title: 幻有传禅师语录
translator: 明 正传说 圆悟．圆修等编
dynasty: 明
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: L1637-52 语录别集(15) L153-58 幻有传禅师语录 etc.
  path:
    - 17 禅宗部类
    - L1637-52 语录别集(15) L153-58 幻有传禅师语录 etc.
  kind: 经
  source: bulei.txt
juan_count: 10
source_xml:
  - L/L153/L153n1637.xml
