cbeta_id: B32n0176
title: 四宗要文
translator: 日朝着　英园纂补
category: 新编（新增及近现代文献）
bulei:
  section_code: "23"
  section: 新编部类
  group: B32
  path:
    - 23 新编部类
    - B0001-198 大藏经补编选录
    - B32
  kind: 疏
  source: bulei.txt
juan_count: 3
source_xml:
  - B/B32/B32n0176.xml
