cbeta_id: N07n0004
title: 长部经典(第15卷-第23卷)
translator: 通妙译
category: 阿含（小乘根本经典）
bulei:
  section_code: "22"
  section: 南传大藏经部类
  group: N0004-23 经藏 N06-47
  path:
    - 22 南传大藏经部类
    - N0004-23 经藏 N06-47
  kind: 经
  source: short
juan_count: 9
source_xml:
  - N/N07/N07n0004.xml
