cbeta_id: T20n1153
title: 普遍光明清净炽盛如意宝印心无能胜大明王大随求陀罗尼经
translator: 唐 不空译
dynasty: 唐
category: 密教（真言宗、陀罗尼、仪轨）
bulei:
  section_code: "10"
  section: 密教部类
  group: T1030-1198 etc. 诸菩萨仪轨 T20, X01-02, C071, F24,27, L135
  path:
    - 10 密教部类
    - T18-21, X01-02,23, C071, F24,27-28, L135, G052 密教部
    - T1030-1198 etc. 诸菩萨仪轨 T20, X01-02, C071, F24,27, L135
    - T1153-56, F1061 大随求陀罗尼
  kind: 经
  source: bulei.txt
juan_count: 2
source_xml:
  - T/T20/T20n1153.xml
