cbeta_id: J37nB384
title: 憨休禅师敲空遗响
translator: 清 如干说　张恂编阅　继尧校订（依驹本印）
dynasty: 清
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: JB090-497 杂着(4) J20-21,23,25-40 续原教论 etc.
  path:
    - 17 禅宗部类
    - JB090-497 杂着(4) J20-21,23,25-40 续原教论 etc.
  kind: 经
  source: bulei.txt
juan_count: 12
source_xml:
  - J/J37/J37nB384.xml
