cbeta_id: T12n0394
title: 佛入涅槃密迹金刚力士哀恋经
translator: 失译
category: 涅槃
bulei:
  section_code: "07"
  section: 涅槃部类
  group: T0377-88,90-96, F0248 涅槃经余 T12b, F03
  path:
    - 07 涅槃部类
    - T0377-88,90-96, F0248 涅槃经余 T12b, F03
  kind: 疏
  source: bulei.txt
juan_count: 1
source_xml:
  - T/T12/T12n0394.xml
