cbeta_id: T51n2081
title: 两部大法相承师资付法记
translator: 唐 海云记
dynasty: 唐
category: 史传（僧传、寺志、编年史料）
bulei:
  section_code: "18"
  section: 史传部类
  group: 18 史传部类 T47,49-52,54, X02,53,75-88 etc.
  path:
    - 18 史传部类
  kind: 疏
  source: bulei.txt
juan_count: 2
source_xml:
  - T/T51/T51n2081.xml
