cbeta_id: X24n0465
title: 金刚经采微余释
translator: 宋 昙应述
dynasty: 宋
category: 般若
bulei:
  section_code: "03"
  section: 般若部类
  group: T1698-1704 etc. 金刚经疏 T33, X24-25, J31, P187, F03
  path:
    - 03 般若部类
    - 07 金刚般若经(大般若经第9会) T07-08, K05／论 T25／疏 T33,40,85, X24-25, J31, P187, F03／礼忏
      X74
    - T1698-1704 etc. 金刚经疏 T33, X24-25, J31, P187, F03
    - X0463-5 金刚经采微科 etc. X24
  kind: 疏
  source: bulei.txt
juan_count: 1
source_xml:
  - X/X24/X24n0465.xml
