cbeta_id: T47n1990
title: 袁州仰山慧寂禅师语录
translator: 明 语风圆信．郭凝之编
dynasty: 明
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: T1989-90 沩仰宗 T47
  path:
    - 17 禅宗部类
    - T1985-2002, JA042 五家语录类 T47-48, J01, M59
    - T1989-90 沩仰宗 T47
  kind: 经
  source: bulei.txt
juan_count: 1
source_xml:
  - T/T47/T47n1990.xml
