cbeta_id: X55n0912
title: 观心诵经法记
translator: 隋 智𫖮说　唐 湛然述
dynasty: 隋
category: 法华
bulei:
  section_code: "04"
  section: 法华部类
  group: T46, X55-57,74, G069,157, P167,189 天台宗
  path:
    - 04 法华部类
    - T46, X55-57,74, G069,157, P167,189 天台宗
  kind: 疏
  source: bulei.txt
juan_count: 1
source_xml:
  - X/X55/X55n0912.xml
