cbeta_id: X74n1470
title: 华严经海印道场忏仪
translator: 唐 一行慧觉依经录　宋 普瑞补注　明 读彻参阅　明 木增订正　明 正止治定
dynasty: 唐
category: 华严
bulei:
  section_code: "05"
  section: 华严部类
  group: X1469-78, F1076 华严礼忏仪 etc.
  path:
    - 05 华严部类
    - T45, X03,08-09,58,74, F28 华严宗
    - X1469-78, F1076 华严礼忏仪 etc.
  kind: 疏
  source: bulei.txt
juan_count: 42
source_xml:
  - X/X74/X74n1470.xml
