cbeta_id: J40nB479
title: 昭觉竹峰续禅师语录
translator: 清 真续说　实悟等编（依驹本增入并印）
dynasty: 清
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: JB472-494 语录别集(14) J40 大博干禅师语录 etc.
  path:
    - 17 禅宗部类
    - JB472-494 语录别集(14) J40 大博干禅师语录 etc.
  kind: 经
  source: bulei.txt
juan_count: 6
source_xml:
  - J/J40/J40nB479.xml
