cbeta_id: J29nB244
title: 三山来禅师语录
translator: 清 灯来说　普定编（原目二十八卷　卷十七下注有「嗣刻」二字　此为初刻本）
dynasty: 清
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: JB222-249 语录别集(8) J29 夔州卧龙字水禅师语录 etc.
  path:
    - 17 禅宗部类
    - JB222-249 语录别集(8) J29 夔州卧龙字水禅师语录 etc.
  kind: 经
  source: bulei.txt
juan_count: 16
source_xml:
  - J/J29/J29nB244.xml
