cbeta_id: X70n1386
title: 石田法薰禅师语录
translator: (门人)了觉．师坦 等编
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: X1374-1403 语录别集(2) X70 龙源介清禅师语录 etc.
  path:
    - 17 禅宗部类
    - X1374-1403 语录别集(2) X70 龙源介清禅师语录 etc.
  kind: 经
  source: bulei.txt
juan_count: 4
source_xml:
  - X/X70/X70n1386.xml
