cbeta_id: X55n0913
title: 天台智者大师发愿文
translator: 隋 智𫖮撰
dynasty: 隋
category: 法华
bulei:
  section_code: "04"
  section: 法华部类
  group: T46, X55-57,74, G069,157, P167,189 天台宗
  path:
    - 04 法华部类
    - T46, X55-57,74, G069,157, P167,189 天台宗
  kind: 疏
  source: bulei.txt
juan_count: 1
source_xml:
  - X/X55/X55n0913.xml
