cbeta_id: J40nB488
title: 斗南𬀩禅师语录
translator: 清 𬀩说　普润等录（依驹本增入并印）
dynasty: 清 𬀩说
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: JB472-494 语录别集(14) J40 大博干禅师语录 etc.
  path:
    - 17 禅宗部类
    - JB472-494 语录别集(14) J40 大博干禅师语录 etc.
  kind: 经
  source: bulei.txt
juan_count: 3
source_xml:
  - J/J40/J40nB488.xml
