cbeta_id: T38n1775
title: 注维摩诘经
translator: 后秦 僧肇撰
dynasty: 后秦
category: 经集（零散大乘经典）
bulei:
  section_code: "09"
  section: 经集部类
  group: T0474-76 维摩诘经 T14／疏 T38,85, X18-19, G103,124
  path:
    - 09 经集部类
    - T0458-601, X0026-27 所问经 etc. T14-15, X01／疏 T38,T85, X18-20,39, G103,124
    - T0474-76 维摩诘经 T14／疏 T38,85, X18-19, G103,124
  kind: 疏
  source: bulei.txt
juan_count: 10
source_xml:
  - T/T38/T38n1775.xml
