cbeta_id: T45n1885
title: 注华严经题法界观门颂
translator: 宋 本嵩述．琮湛注
dynasty: 宋
category: 华严
bulei:
  section_code: "05"
  section: 华严部类
  group: T1883-85, X1007-08 华严法界观门 etc.
  path:
    - 05 华严部类
    - T45, X03,08-09,58,74, F28 华严宗
    - T1883-85, X1007-08 华严法界观门 etc.
  kind: 疏
  source: bulei.txt
juan_count: 2
source_xml:
  - T/T45/T45n1885.xml
