cbeta_id: J29nB234
title: 一初元禅师语录
translator: 清 元说　真开．真智等编
dynasty: 清 元说
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: JB222-249 语录别集(8) J29 夔州卧龙字水禅师语录 etc.
  path:
    - 17 禅宗部类
    - JB222-249 语录别集(8) J29 夔州卧龙字水禅师语录 etc.
  kind: 经
  source: bulei.txt
juan_count: 2
source_xml:
  - J/J29/J29nB234.xml
