cbeta_id: J33nB285
title: 兜率不磷坚禅师语录
translator: 清 宗坚说　妙圣等记
dynasty: 清
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: JB272-313 语录别集(9) J32-34 明州天童景德禅寺宏智觉禅师语录 etc.
  path:
    - 17 禅宗部类
    - JB272-313 语录别集(9) J32-34 明州天童景德禅寺宏智觉禅师语录 etc.
  kind: 经
  source: bulei.txt
juan_count: 3
source_xml:
  - J/J33/J33nB285.xml
