cbeta_id: J38nB422
title: 林我禅师语录
translator: 清 鉴说　海錱．海兹等编录（依驹本印）
dynasty: 清 鉴说
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: JB406-434 语录别集(12) J38 庐山天然禅师语录 etc.
  path:
    - 17 禅宗部类
    - JB406-434 语录别集(12) J38 庐山天然禅师语录 etc.
  kind: 经
  source: bulei.txt
juan_count: 4
source_xml:
  - J/J38/J38nB422.xml
