cbeta_id: X73n1452
title: 紫柏尊者全集
translator: 明 德清阅
dynasty: 明
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: X1445-58, JB116 语录别集(5) X73, J22 玄沙师备禅师广录 etc.
  path:
    - 17 禅宗部类
    - X1445-58, JB116 语录别集(5) X73, J22 玄沙师备禅师广录 etc.
  kind: 经
  source: bulei.txt
juan_count: 29
source_xml:
  - X/X73/X73n1452.xml
