cbeta_id: X03n0211
title: 华严经文义记〔卷六〕
translator: 隋 灵裕集记
dynasty: 隋
category: 华严
bulei:
  section_code: "05"
  section: 华严部类
  group: T45, X03,08-09,58,74, F28 华严宗
  path:
    - 05 华严部类
    - T45, X03,08-09,58,74, F28 华严宗
  kind: 疏
  source: bulei.txt
juan_count: 1
source_xml:
  - X/X03/X03n0211.xml
