cbeta_id: L158n1652
title: 明觉聪禅师语录
translator: 清 性聪撰述 寂空．方醒等编次
dynasty: 清
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: L1637-52 语录别集(15) L153-58 幻有传禅师语录 etc.
  path:
    - 17 禅宗部类
    - L1637-52 语录别集(15) L153-58 幻有传禅师语录 etc.
  kind: 经
  source: bulei.txt
juan_count: 20
source_xml:
  - L/L158/L158n1652.xml
