cbeta_id: T18n0908
title: 金刚顶瑜伽护摩仪轨
translator: 唐 不空译
dynasty: 唐
category: 密教（真言宗、陀罗尼、仪轨）
bulei:
  section_code: "10"
  section: 密教部类
  group: T0908-14 护摩仪轨 etc. T18
  path:
    - 10 密教部类
    - T18-21, X01-02,23, C071, F24,27-28, L135, G052 密教部
    - T0908-14 护摩仪轨 etc. T18
  kind: 经
  source: bulei.txt
juan_count: 1
source_xml:
  - T/T18/T18n0908.xml
