cbeta_id: X84n1581
title: 皇明名僧辑略
translator: 明 袾宏辑
dynasty: 明
category: 史传（僧传、寺志、编年史料）
bulei:
  section_code: "18"
  section: 史传部类
  group: X1581,1606,08,1616-21, JB125 明清禅宗史传
  path:
    - 18 史传部类
    - T2075-80,1998B, X1553-1622, JB125 禅宗传 T51,47, X78-87, J23, P154-55
    - X1581,1606,08,1616-21, JB125 明清禅宗史传
  kind: 疏
  source: bulei.txt
juan_count: 1
source_xml:
  - X/X84/X84n1581.xml
