cbeta_id: J34nB310
title: 云叟住禅师语录
translator: 清 住说　元一记录
dynasty: 清 住说
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: JB272-313 语录别集(9) J32-34 明州天童景德禅寺宏智觉禅师语录 etc.
  path:
    - 17 禅宗部类
    - JB272-313 语录别集(9) J32-34 明州天童景德禅寺宏智觉禅师语录 etc.
  kind: 经
  source: bulei.txt
juan_count: 2
source_xml:
  - J/J34/J34nB310.xml
