cbeta_id: X71n1414
title: 了庵清欲禅师语录
translator: (参学)一志．元皓．可兴．文康．祖运．志道．祖杲．得度．文焕．克明．宗成．宗胤．起宗．汝现．元宝．慧朗．景毅．大圆．海寿．祖灊 等编
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: X1404-26 语录别集(3) X71 兀庵普宁禅师语录 etc.
  path:
    - 17 禅宗部类
    - X1404-26 语录别集(3) X71 兀庵普宁禅师语录 etc.
  kind: 经
  source: bulei.txt
juan_count: 9
source_xml:
  - X/X71/X71n1414.xml
