cbeta_id: X70n1382
title: 无准师范禅师语录
translator: (侍者)宗会．智折．觉圆．如海．妙伦．惟一．了禅．了心．普明．了南．绍昙．了觉．师坦．妙因．至慧 编
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: X1374-1403 语录别集(2) X70 龙源介清禅师语录 etc.
  path:
    - 17 禅宗部类
    - X1374-1403 语录别集(2) X70 龙源介清禅师语录 etc.
  kind: 经
  source: bulei.txt
juan_count: 5
source_xml:
  - X/X70/X70n1382.xml
