cbeta_id: X73n1454
title: 云谷和尚语录
translator: (参学)宗敬．道杰．惟能．宗．祖禄 编㞧
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: X1445-58, JB116 语录别集(5) X73, J22 玄沙师备禅师广录 etc.
  path:
    - 17 禅宗部类
    - X1445-58, JB116 语录别集(5) X73, J22 玄沙师备禅师广录 etc.
  kind: 经
  source: bulei.txt
juan_count: 2
source_xml:
  - X/X73/X73n1454.xml
