cbeta_id: X66n1297
title: 宗鉴法林
translator: 清 集云堂编
dynasty: 清
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: X1296-98 语录通集(2) X66 拈古汇集 etc.
  path:
    - 17 禅宗部类
    - X1296-98 语录通集(2) X66 拈古汇集 etc.
  kind: 经
  source: bulei.txt
juan_count: 72
source_xml:
  - X/X66/X66n1297.xml
