cbeta_id: ZW04n0033
title: 入菩萨行论广解
translator: 寂天菩萨造颂　杰操大师注解　隆莲法师译
category: 新编（新增及近现代文献）
bulei:
  section_code: "23"
  section: 新编部类
  group: ZW0033-44 第四辑
  path:
    - 23 新编部类
    - ZW0001-103 藏外佛教文献
    - ZW0033-44 第四辑
    - ZW0033 汉译藏文佛典
  kind: 疏
  source: bulei.txt
juan_count: 10
source_xml:
  - ZW/ZW04/ZW04n0033.xml
