cbeta_id: N69n0035
title: 清净道论(第14卷-第23卷)
translator: 佛音撰　悟醒译
category: 论集（杂论、通论）
bulei:
  section_code: "22"
  section: 南传大藏经部类
  group: N0031-38 藏外 N63-70
  path:
    - 22 南传大藏经部类
    - N0031-38 藏外 N63-70
  kind: 经
  source: short
juan_count: 10
source_xml:
  - N/N69/N69n0035.xml
