cbeta_id: J29nB223
title: 山晖禅师语录
translator: 清 璧说　如崇等录　宗上编
dynasty: 清 璧说
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: JB222-249 语录别集(8) J29 夔州卧龙字水禅师语录 etc.
  path:
    - 17 禅宗部类
    - JB222-249 语录别集(8) J29 夔州卧龙字水禅师语录 etc.
  kind: 经
  source: bulei.txt
juan_count: 12
source_xml:
  - J/J29/J29nB223.xml
