cbeta_id: J40nB494
title: 雨山和尚语录
translator: 清 上思说
dynasty: 清
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: JB472-494 语录别集(14) J40 大博干禅师语录 etc.
  path:
    - 17 禅宗部类
    - JB472-494 语录别集(14) J40 大博干禅师语录 etc.
  kind: 经
  source: bulei.txt
juan_count: 20
source_xml:
  - J/J40/J40nB494.xml
