cbeta_id: X67n1299
title: 禅林类聚
translator: 元 道泰集
dynasty: 元
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: X1299-1313 语录通集(3) X67 禅林类聚 etc.
  path:
    - 17 禅宗部类
    - X1299-1313 语录通集(3) X67 禅林类聚 etc.
  kind: 经
  source: bulei.txt
juan_count: 20
source_xml:
  - X/X67/X67n1299.xml
