cbeta_id: N49n0025
title: 分别论(第1卷-第15卷)
translator: 郭哲彰译
category: 论集（杂论、通论）
bulei:
  section_code: "22"
  section: 南传大藏经部类
  group: N0024-30 论藏 N48-62
  path:
    - 22 南传大藏经部类
    - N0024-30 论藏 N48-62
  kind: 经
  source: bulei.txt
juan_count: 15
source_xml:
  - N/N49/N49n0025.xml
