cbeta_id: J23nB128
title: 普明禅师牧牛图颂
translator: 明 普明原唱　诸方和韵　严大参序　清 如念编目　有图十
dynasty: 明
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: X1260-76, JB128-29 杂着(2) X64, J23 列祖提纲录 etc.
  path:
    - 17 禅宗部类
    - X1260-76, JB128-29 杂着(2) X64, J23 列祖提纲录 etc.
  kind: 经
  source: bulei.txt
juan_count: 1
source_xml:
  - J/J23/J23nB128.xml
