cbeta_id: T32n1628
title: 因明正理门论本
translator: 大域龙菩萨造  唐 玄奘译
category: 论集（杂论、通论）
bulei:
  section_code: "15"
  section: 论集部类
  group: T1628-33 因明论 etc. T32
  path:
    - 15 论集部类
    - T1628-33 因明论 etc. T32／疏 T44a, X53, A119
    - T1628-33 因明论 etc. T32
  kind: 疏
  source: bulei.txt
juan_count: 1
source_xml:
  - T/T32/T32n1628.xml
