cbeta_id: J34nB305
title: 国清大庾韬禅师语录
translator: 清 行韬说　显裕等录　有塔铭　行略（依驹本印）
dynasty: 清
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: JB272-313 语录别集(9) J32-34 明州天童景德禅寺宏智觉禅师语录 etc.
  path:
    - 17 禅宗部类
    - JB272-313 语录别集(9) J32-34 明州天童景德禅寺宏智觉禅师语录 etc.
  kind: 经
  source: bulei.txt
juan_count: 1
source_xml:
  - J/J34/J34nB305.xml
