cbeta_id: T12n0337
title: 佛说阿阇贳王女阿术达菩萨经
translator: 西晋 竺法护译
dynasty: 西晋
category: 宝积
bulei:
  section_code: "06"
  section: 宝积部类
  group: T0311-54 宝积经异译
  path:
    - 06 宝积部类
    - T0310-73 宝积部 T11-12a
    - T0311-54 宝积经异译
  kind: 经
  source: bulei.txt
juan_count: 1
source_xml:
  - T/T12/T12n0337.xml
