cbeta_id: ZW07n0060
title: 金刚礼
translator: 辽 通理大师集　达照整理
dynasty: 辽
category: 新编（新增及近现代文献）
bulei:
  section_code: "23"
  section: 新编部类
  group: ZW0058-66 第七辑
  path:
    - 23 新编部类
    - ZW0001-103 藏外佛教文献
    - ZW0058-66 第七辑
    - ZW0059-60 佛教仪轨
  kind: 疏
  source: bulei.txt
juan_count: 1
source_xml:
  - ZW/ZW07/ZW07n0060.xml
