cbeta_id: T12n0384
title: 菩萨从兜术天降神母胎说广普经
translator: 姚秦 竺佛念译
dynasty: 姚秦
category: 涅槃
bulei:
  section_code: "07"
  section: 涅槃部类
  group: T0377-88,90-96, F0248 涅槃经余 T12b, F03
  path:
    - 07 涅槃部类
    - T0377-88,90-96, F0248 涅槃经余 T12b, F03
  kind: 疏
  source: bulei.txt
juan_count: 7
source_xml:
  - T/T12/T12n0384.xml
