cbeta_id: X67n1302
title: 焭绝老人天奇直注雪窦显和尚颂古
translator: 明 本瑞直注　道霖．性福编集
dynasty: 明
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: X1299-1313 语录通集(3) X67 禅林类聚 etc.
  path:
    - 17 禅宗部类
    - X1299-1313 语录通集(3) X67 禅林类聚 etc.
  kind: 经
  source: bulei.txt
juan_count: 2
source_xml:
  - X/X67/X67n1302.xml
