cbeta_id: B25n0145
title: 天目中峰广录
translator: 中峰明本着
category: 新编（新增及近现代文献）
bulei:
  section_code: "23"
  section: 新编部类
  group: B25
  path:
    - 23 新编部类
    - B0001-198 大藏经补编选录
    - B25
  kind: 疏
  source: bulei.txt
juan_count: 30
source_xml:
  - B/B25/B25n0145.xml
