cbeta_id: J29nB225
title: 鄂州龙光达夫禅师鸡肋集
translator: 清 蕴上说　道汜．道冲等录（依驹本印）
dynasty: 清
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: JB090-497 杂着(4) J20-21,23,25-40 续原教论 etc.
  path:
    - 17 禅宗部类
    - JB090-497 杂着(4) J20-21,23,25-40 续原教论 etc.
  kind: 经
  source: bulei.txt
juan_count: 1
source_xml:
  - J/J29/J29nB225.xml
