cbeta_id: X73n1451
title: 慈受怀深禅师广录
translator: (侍者)善清．善随．宗先．普绍 编
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: X1445-58, JB116 语录别集(5) X73, J22 玄沙师备禅师广录 etc.
  path:
    - 17 禅宗部类
    - X1445-58, JB116 语录别集(5) X73, J22 玄沙师备禅师广录 etc.
  kind: 经
  source: bulei.txt
juan_count: 4
source_xml:
  - X/X73/X73n1451.xml
