cbeta_id: J27nB199
title: 雪关和尚语录
translator: 明 智訚说　传善辑
dynasty: 明
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: JB189-221 语录别集(7) J27-28 三宜盂禅师语录 etc.
  path:
    - 17 禅宗部类
    - JB189-221 语录别集(7) J27-28 三宜盂禅师语录 etc.
  kind: 经
  source: bulei.txt
juan_count: 6
source_xml:
  - J/J27/J27nB199.xml
