cbeta_id: B23n0130
title: 灵峰宗论（选录〈蕅益大师年谱〉、〈书重刻灵峰宗论后〉、〈刻辟邪集序〉）
translator: 智旭着
category: 新编（新增及近现代文献）
bulei:
  section_code: "23"
  section: 新编部类
  group: B23
  path:
    - 23 新编部类
    - B0001-198 大藏经补编选录
    - B23
    - B0130 (=JB348+JB120+X1641+选录) 灵峰宗论（选录〈蕅益大师年谱〉、〈书重刻灵峰宗论后〉、〈刻辟邪集序〉）
  kind: 疏
  source: bulei.txt
juan_count: 1
source_xml:
  - B/B23/B23n0130.xml
