cbeta_id: J26nB185
title: 浮石禅师语录
translator: 明 通贤说　行浚等编
dynasty: 明
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: JA158,B137-188 语录别集(6) J10,24-26 密云禅师语录 etc.
  path:
    - 17 禅宗部类
    - JA158,B137-188 语录别集(6) J10,24-26 密云禅师语录 etc.
  kind: 经
  source: bulei.txt
juan_count: 10
source_xml:
  - J/J26/J26nB185.xml
