cbeta_id: T32n1643
title: 尼乾子问无我义经
translator: 马鸣菩萨集  宋 日称译
category: 论集（杂论、通论）
bulei:
  section_code: "15"
  section: 论集部类
  group: T1639-43 外道四宗论 etc. T32
  path:
    - 15 论集部类
    - T1639-43 外道四宗论 etc. T32
  kind: 疏
  source: bulei.txt
juan_count: 1
source_xml:
  - T/T32/T32n1643.xml
