cbeta_id: T85n2779
title: 佛说楞伽经禅门悉谈章
category: 敦煌写本（敦煌出土古写经）
bulei:
  section_code: "09"
  section: 经集部类
  group: T0670-74, X0008 楞伽经 etc. T16, X01／疏 T39,85, X17-18, C097
  path:
    - 09 经集部类
    - T0670-74, X0008 楞伽经 etc. T16, X01／疏 T39,85, X17-18, C097
  kind: 疏
  source: bulei.txt
juan_count: 1
source_xml:
  - T/T85/T85n2779.xml
