cbeta_id: T55n2178
title: 天台宗章疏
translator: 日本 玄日录
dynasty: 日本
category: 事汇（类书、辞典、法数典籍）
bulei:
  section_code: "19"
  section: 事汇部类
  group: T2176-84 etc. 日本高丽诸宗目录
  path:
    - 19 事汇部类
    - T2145-84, JB271 目录部 T55, J31-32, A097-098,110-112, L143, C106, K38
    - T2176-84 etc. 日本高丽诸宗目录
  kind: 疏
  source: bulei.txt
juan_count: 1
source_xml:
  - T/T55/T55n2178.xml
