cbeta_id: J34nB304
title: 灵树远禅师云嵒集
translator: 清 僧远说　广仍记　附云嵒颂古　附云嵒九颂　余怀制
dynasty: 清
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: JB090-497 杂着(4) J20-21,23,25-40 续原教论 etc.
  path:
    - 17 禅宗部类
    - JB090-497 杂着(4) J20-21,23,25-40 续原教论 etc.
  kind: 经
  source: bulei.txt
juan_count: 2
source_xml:
  - J/J34/J34nB304.xml
