cbeta_id: T85n2740
title: 金刚般若义记
category: 敦煌写本（敦煌出土古写经）
bulei:
  section_code: "03"
  section: 般若部类
  group: T2732-43 金刚经古逸疏 T85
  path:
    - 03 般若部类
    - 07 金刚般若经(大般若经第9会) T07-08, K05／论 T25／疏 T33,40,85, X24-25, J31, P187, F03／礼忏
      X74
    - T2732-43 金刚经古逸疏 T85
  kind: 疏
  source: bulei.txt
juan_count: 1
source_xml:
  - T/T85/T85n2740.xml
