cbeta_id: I00na001
title: 北朝佛教石刻拓片百品．说明
translator: 财团法人佛教电子佛典基金会
category: 史传（僧传、寺志、编年史料）
bulei:
  section_code: "23"
  section: 新编部类
  group: I0001-100 北朝佛教石刻拓片百品
  path:
    - 23 新编部类
    - I0001-100 北朝佛教石刻拓片百品
  kind: 疏
  source: bulei.txt
juan_count: 1
source_xml:
  - I/I00/I00nA001.xml
