cbeta_id: X57n0978
title: 四教仪集注科
translator: 元 蒙润排定
dynasty: 元
category: 法华
bulei:
  section_code: "04"
  section: 法华部类
  group: T1931, X0976-80, P1629 天台四教仪 etc.
  path:
    - 04 法华部类
    - T46, X55-57,74, G069,157, P167,189 天台宗
    - T1931, X0976-80, P1629 天台四教仪 etc.
  kind: 疏
  source: bulei.txt
juan_count: 1
source_xml:
  - X/X57/X57n0978.xml
