cbeta_id: J28nB216
title: 绝余编
translator: 明 智旭着　圆果录
dynasty: 明
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: JB090-497 杂着(4) J20-21,23,25-40 续原教论 etc.
  path:
    - 17 禅宗部类
    - JB090-497 杂着(4) J20-21,23,25-40 续原教论 etc.
  kind: 经
  source: bulei.txt
juan_count: 4
source_xml:
  - J/J28/J28nB216.xml
