cbeta_id: J24nB137
title: 赵州和尚语录
translator: 唐 从谂说　文远记　大参重校　明声重刻
dynasty: 唐
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: JA158,B137-188 语录别集(6) J10,24-26 密云禅师语录 etc.
  path:
    - 17 禅宗部类
    - JA158,B137-188 语录别集(6) J10,24-26 密云禅师语录 etc.
  kind: 经
  source: bulei.txt
juan_count: 3
source_xml:
  - J/J24/J24nB137.xml
