cbeta_id: T25n1517
title: 佛母般若波罗蜜多圆集要义释论
translator: 三宝尊菩萨造  大域龙菩萨造本论  宋 施护等译
category: 般若
zaijia:
  section: 般若部類
  topic: 小品般若經(大般若經第4-5會)
  kind: 疏
juan_count: 4
source_xml:
  - T/T25/T25n1517.xml
