cbeta_id: J27nB191
title: 象田即念禅师语录
translator: 明 净现说　净痴等录
dynasty: 明
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: JB189-221 语录别集(7) J27-28 三宜盂禅师语录 etc.
  path:
    - 17 禅宗部类
    - JB189-221 语录别集(7) J27-28 三宜盂禅师语录 etc.
  kind: 经
  source: bulei.txt
juan_count: 4
source_xml:
  - J/J27/J27nB191.xml
