cbeta_id: J40nB484
title: 野云映禅师宗统颂
translator: 清 灯映颂　性灿录　有塔铭　行状（依驹本增入并印　原书第二十三页起至末页缺）
dynasty: 清
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: JB090-497 杂着(4) J20-21,23,25-40 续原教论 etc.
  path:
    - 17 禅宗部类
    - JB090-497 杂着(4) J20-21,23,25-40 续原教论 etc.
  kind: 经
  source: bulei.txt
juan_count: 1
source_xml:
  - J/J40/J40nB484.xml
