cbeta_id: J29nB242
title: 铁眉三巴掌禅师语录
translator: 明 铁眉号三巴掌说　性养．性亮同编
dynasty: 明
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: JB222-249 语录别集(8) J29 夔州卧龙字水禅师语录 etc.
  path:
    - 17 禅宗部类
    - JB222-249 语录别集(8) J29 夔州卧龙字水禅师语录 etc.
  kind: 经
  source: bulei.txt
juan_count: 1
source_xml:
  - J/J29/J29nB242.xml
