cbeta_id: T19n0954B
title: 一字顶轮王念诵仪轨
category: 密教（真言宗、陀罗尼、仪轨）
bulei:
  section_code: "10"
  section: 密教部类
  group: T0944-81 etc. 诸佛顶仪轨 T19, G052, F27
  path:
    - 10 密教部类
    - T18-21, X01-02,23, C071, F24,27-28, L135, G052 密教部
    - T0944-81 etc. 诸佛顶仪轨 T19, G052, F27
  kind: 经
  source: bulei.txt
juan_count: 1
source_xml:
  - T/T19/T19n0954B.xml
