cbeta_id: X71n1418
title: 呆庵普庄禅师语录
translator: (门人)慧启．智粤．智胜．德琇．昙顿．道哲 等编
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: X1404-26 语录别集(3) X71 兀庵普宁禅师语录 etc.
  path:
    - 17 禅宗部类
    - X1404-26 语录别集(3) X71 兀庵普宁禅师语录 etc.
  kind: 经
  source: bulei.txt
juan_count: 8
source_xml:
  - X/X71/X71n1418.xml
