cbeta_id: J31nB269
title: 金剛般若經疏論纂要刊定記會編
translator: 唐 宗密述疏　宋 子璿錄記　清 行策會編
dynasty: 唐
category: 般若
zaijia:
  section: 般若部類
  topic: 金剛般若經(大般若經第9會)
  kind: 疏
juan_count: 10
source_xml:
  - J/J31/J31nB269.xml
