cbeta_id: T15n0595
title: 佛说嗟韈囊法天子受三归依获免恶道经
translator: 宋 法天译
dynasty: 宋
category: 经集（零散大乘经典）
bulei:
  section_code: "09"
  section: 经集部类
  group: T0458-601, X0026-27 所问经 etc. T14-15, X01／疏 T38,T85, X18-20,39, G103,124
  path:
    - 09 经集部类
    - T0458-601, X0026-27 所问经 etc. T14-15, X01／疏 T38,T85, X18-20,39, G103,124
  kind: 疏
  source: bulei.txt
juan_count: 1
source_xml:
  - T/T15/T15n0595.xml
