cbeta_id: X70n1377
title: 松源崇岳禅师语录
translator: (参学)善开．光睦．普岩．师肇．道岩．了能 等录
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: X1374-1403 语录别集(2) X70 龙源介清禅师语录 etc.
  path:
    - 17 禅宗部类
    - X1374-1403 语录别集(2) X70 龙源介清禅师语录 etc.
  kind: 经
  source: bulei.txt
juan_count: 2
source_xml:
  - X/X70/X70n1377.xml
