cbeta_id: X69n1367
title: 笑隐大䜣禅师语录
translator: (门人)延俊．慧昙．中孚．崇裕 等编
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: X1320-72, JB134 语录别集(1) X69, J23 四家语录 etc.
  path:
    - 17 禅宗部类
    - X1320-72, JB134 语录别集(1) X69, J23 四家语录 etc.
  kind: 经
  source: bulei.txt
juan_count: 4
source_xml:
  - X/X69/X69n1367.xml
