cbeta_id: J40nB472
title: 大博干禅师语录
translator: 清 干说　超宗等录（依驹本增入并印）
dynasty: 清 干说
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: JB472-494 语录别集(14) J40 大博干禅师语录 etc.
  path:
    - 17 禅宗部类
    - JB472-494 语录别集(14) J40 大博干禅师语录 etc.
  kind: 经
  source: bulei.txt
juan_count: 5
source_xml:
  - J/J40/J40nB472.xml
