cbeta_id: F03n0089
title: 佛说恒水流树经
translator: 刘宋 天竺三藏求那跋陀罗译
dynasty: 刘宋
category: 阿含（小乘根本经典）
bulei:
  section_code: "01"
  section: 阿含部类
  group: T0101-0124, F0089 杂阿含经单本
  path:
    - 01 阿含部类
    - T0099-124, F0089 杂阿含经 etc. T02, F03
    - T0101-0124, F0089 杂阿含经单本
  kind: 经
  source: bulei.txt
juan_count: 1
source_xml:
  - F/F03/F03n0089.xml
