cbeta_id: X23n0445
title: 佛顶尊胜陀罗尼经释
translator: 清 续法释
dynasty: 清
category: 密教（真言宗、陀罗尼、仪轨）
bulei:
  section_code: "10"
  section: 密教部类
  group: T1803, X0445 佛顶尊胜陀罗尼经教迹义记 etc. T39, X23
  path:
    - 10 密教部类
    - T39, X10-16,23,  P168,185 密教疏
    - T1803, X0445 佛顶尊胜陀罗尼经教迹义记 etc. T39, X23
  kind: 疏
  source: bulei.txt
juan_count: 1
source_xml:
  - X/X23/X23n0445.xml
