cbeta_id: J36nB358
title: 智覃正禅师语录
translator: 清 最正说　尚能．尚莹等编　末附助缘耆德
dynasty: 清
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: JB336-369 语录别集(10) J35-36 南海宝象林慧弓诇禅师语录 etc.
  path:
    - 17 禅宗部类
    - JB336-369 语录别集(10) J35-36 南海宝象林慧弓诇禅师语录 etc.
  kind: 经
  source: bulei.txt
juan_count: 1
source_xml:
  - J/J36/J36nB358.xml
