cbeta_id: J31nB271
title: 阅藏知津(第1卷-第5卷)
translator: 明 智旭汇辑　总目四卷
dynasty: 明
category: 事汇（类书、辞典、法数典籍）
bulei:
  section_code: "19"
  section: 事汇部类
  group: T2145-58 etc.中国译经目录
  path:
    - 19 事汇部类
    - T2145-84, JB271 目录部 T55, J31-32, A097-098,110-112, L143, C106, K38
    - T2145-58 etc.中国译经目录
  kind: 疏
  source: bulei.txt
juan_count: 5
source_xml:
  - J/J31/J31nB271.xml
