cbeta_id: X71n1416
title: 恕中无愠禅师语录
translator: (嗣法参学)宗黼．道瑄．宗亘．居顶．惟寂．宗寄．慧浩．清岁 等编
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: X1404-26 语录别集(3) X71 兀庵普宁禅师语录 etc.
  path:
    - 17 禅宗部类
    - X1404-26 语录别集(3) X71 兀庵普宁禅师语录 etc.
  kind: 经
  source: bulei.txt
juan_count: 6
source_xml:
  - X/X71/X71n1416.xml
