cbeta_id: N57n0029
title: 发趣论(第7卷)
translator: 郭哲彰译
category: 论集（杂论、通论）
bulei:
  section_code: "22"
  section: 南传大藏经部类
  group: N0024-30 论藏 N48-62
  path:
    - 22 南传大藏经部类
    - N0024-30 论藏 N48-62
  kind: 经
  source: short
juan_count: 1
source_xml:
  - N/N57/N57n0029.xml
