cbeta_id: N02n0001
title: 经分别(第5卷-第15卷)
translator: 通妙译
category: 律部（戒律、僧制）
bulei:
  section_code: "22"
  section: 南传大藏经部类
  group: N0001-03 律藏 N01-05
  path:
    - 22 南传大藏经部类
    - N0001-03 律藏 N01-05
  kind: 经
  source: short
juan_count: 11
source_xml:
  - N/N02/N02n0001.xml
