cbeta_id: X72n1444
title: 湛然圆澄禅师语录
translator: (门人)明凡录　丁元公．祁骏隹 编
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: X1428-44 语录别集(4) X72 净慈慧晖禅师语录 etc.
  path:
    - 17 禅宗部类
    - X1428-44 语录别集(4) X72 净慈慧晖禅师语录 etc.
  kind: 经
  source: bulei.txt
juan_count: 8
source_xml:
  - X/X72/X72n1444.xml
