cbeta_id: X74n1480
title: 千手千眼大悲心咒行法
translator: 宋 知礼始集　清 读体重纂
dynasty: 宋
category: 法华
bulei:
  section_code: "04"
  section: 法华部类
  group: T1941-51, X1480,88,1501, P1573 天台礼忏仪 etc.
  path:
    - 04 法华部类
    - T46, X55-57,74, G069,157, P167,189 天台宗
    - T1941-51, X1480,88,1501, P1573 天台礼忏仪 etc.
  kind: 疏
  source: bulei.txt
juan_count: 1
source_xml:
  - X/X74/X74n1480.xml
