cbeta_id: X69n1368
title: 偃溪广闻禅师语录
translator: (侍者门人)元清．净志．普晖．元伟．光从．道鉴．道隆．惟实．妙高 编
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: X1320-72, JB134 语录别集(1) X69, J23 四家语录 etc.
  path:
    - 17 禅宗部类
    - X1320-72, JB134 语录别集(1) X69, J23 四家语录 etc.
  kind: 经
  source: bulei.txt
juan_count: 2
source_xml:
  - X/X69/X69n1368.xml
