cbeta_id: T85n2801
title: 瑜伽师地论分门记
translator: 唐 法成撰．智慧山记
dynasty: 唐
category: 敦煌写本（敦煌出土古写经）
bulei:
  section_code: "14"
  section: 瑜伽部类
  group: T1579-84 瑜伽论／疏 T42-43,85, X39,47, A120
  path:
    - 14 瑜伽部类
    - T30b-32 瑜伽行派论／疏 T42-44,85, X39,46-51, A120
    - T1579-84 瑜伽论／疏 T42-43,85, X39,47, A120
  kind: 疏
  source: bulei.txt
juan_count: 6
source_xml:
  - T/T85/T85n2801.xml
