cbeta_id: X70n1376
title: 痴绝道冲禅师语录
translator: (嗣法门人)智沂．悟开．行弥．绍甄．智圆．元省．元枢 编
category: 禅宗
bulei:
  section_code: "17"
  section: 禅宗部类
  group: X1374-1403 语录别集(2) X70 龙源介清禅师语录 etc.
  path:
    - 17 禅宗部类
    - X1374-1403 语录别集(2) X70 龙源介清禅师语录 etc.
  kind: 经
  source: bulei.txt
juan_count: 2
source_xml:
  - X/X70/X70n1376.xml
